# Generated by Django 3.2.5 on 2022-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('customer_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('content', models.BinaryField()),
            ],
        ),
    ]
